### ISSUE TITLE
[chromium] Dockerfile parse error line 10: unknown instruction: EXPORT

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/dockerfiles#143]
It seems like the latest commit ba22b5356746006bedfd57da81ced38f7923947e introduces a Dockerfile syntax error at [line 10](https://github.com/JanitorTechnology/dockerfiles/blob/master/chromium/chromium.dockerfile#L10):

```
Error response from daemon: Dockerfile parse error line 10: unknown instruction: EXPORT
Exited with code 1
```

@beaufortfrancois Maybe the multi-line `cat` doesn't work after all in a Dockerfile?

Build logs: https://circleci.com/gh/JanitorTechnology/dockerfiles/432

**Comment by beaufortfrancois** [comment]
And I just noticed these Docker issues:
- https://github.com/moby/moby/issues/28587
- https://github.com/moby/moby/pull/24725

I'll submit another PR to fix my mistakes shortly.
