### ISSUE TITLE
[all] circleci builds fail due to "hash sum mismatch" on apt.llvm.org

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/dockerfiles#150]
All Dockerfiles contain a variant of the command `sudo apt-get update -q  && sudo apt-get upgrade -qy`.

Currently, all image builds are broken on Circle CI, with the following error:

```
E: Failed to fetch https://apt.llvm.org/xenial/dists/llvm-toolchain-xenial-6.0/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

@Sylvestre is this a known issue?

**Comment by sylvestre** [comment]
Yeah, issue with the CDN :/

**Comment by jankeromnes** [comment]
This didn't happen again and the builds are fixed. Closing this issue. Thanks for the info about the CDN problems!

**Comment by sylvestre** [comment]
This was this bug https://bugs.llvm.org/show_bug.cgi?id=36396
