### ISSUE TITLE
[ubuntu-dev] "bash: __git_ps1: command not found" after every command output

### ISSUE THREAD

**Issue by nt1m** [JanitorTechnology/dockerfiles#179]
/cc @ishitatsuyuki

**Comment by jankeromnes** [comment]
Thanks for reporting! It appears that the Git PPA we switched to doesn't install `__git_ps1` into the `PATH`.

**Comment by ishitatsuyuki** [comment]
I intended to fix it in #178. Please confirm.

**Comment by ishitatsuyuki** [comment]
(This require a new session. Closing.)
