### ISSUE TITLE
[ubuntu-dev] switch git profile build to profile-fast

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/dockerfiles#43]
Currently, we optimize Git builds by running the entire test suite to generate an optimization profile. This makes our CircleCI builds run for 8h+.

Maybe we could switch to using Git's "profile-fast" that only runs benchmarks for the profile instead of the entire test suite. I believe this would still make the resulting binary really fast, but not take as long as 8h+ to achieve.

**Comment by jankeromnes** [comment]
Fixed in b00be2120b98b5ca5da8765be7b1d409edf1020e.

**Comment by jankeromnes** [comment]
That didn't actually work, because Git's `make profile-fast` requires a pre-existing Git repository to run perf tests on. Otherwise, it fails as described in:

https://public-inbox.org/git/CAA6PgK74CTT09RZiQWGoih3x6B5G4tLa_Vz7e9BDNW4+TGdLXw@mail.gmail.com/

A solution to make `make profile-fast` work would be to somehow get a Git repository before having installed Git (e.g. https://github.com/git/git/) and point `$GIT_PERF_REPO` to it. We could do this by either:

- finding a tarball that contains a `.git/` folder somewhere
- using the Git binary compiled by `make all` to clone some repository
- installing Git a first time to clone some repository (and then install it again once optimized)
- installing Ubuntu's Git before building the latest stable Git, and use that to clone some repository

**Comment by ishitatsuyuki** [comment]
We now use PPA, this is obsolete.

**Comment by jankeromnes** [comment]
I really hope that the PPA offers a profile-optimized build! 😄 Closing as this is now out of our hands.
