### ISSUE TITLE
[firefox][thunderbird] build fails with llvm/clang 5.0

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/dockerfiles#86]
```
 0:09.39 checking for llvm-config... not found
 0:09.39 ERROR: Could not find LLVM/Clang installation for compiling stylo build-time
 0:09.39 bindgen.  Please specify the 'LLVM_CONFIG' environment variable
 0:09.39 (recommended), pass the '--with-libclang-path' and '--with-clang-path'
 0:09.39 options to configure, or put 'llvm-config' in your PATH.  Altering your
 0:09.39 PATH may expose 'clang' as well, potentially altering your compiler,
 0:09.39 which may not be what you intended.
 0:09.42 *** Fix above errors and then restart with\
 0:09.42                "/usr/bin/make -f client.mk build"
 0:09.42 client.mk:384: recipe for target 'configure' failed
 0:09.42 make: *** [configure] Error 1
The command '/bin/sh -c ./mach build' returned a non-zero code: 2
Exited with code 2
```

**Comment by jankeromnes** [comment]
Looks like in previous containers, the package `llvm-config-4.0` was auto-detected, but now `llvm-config-5.0` isn't.

**Comment by sylvestre** [comment]
I wonder if this isn't https://bugzilla.mozilla.org/show_bug.cgi?id=1388008 
this stuff is for bindgen, anyway, i still think we should fix 1388008 for Linux

**Comment by jankeromnes** [comment]
@sylvestre Thanks for linking to this issue! However, I'm not sure it's related to our problem, because we don't run `./mach bootstrap`.

We do however download and run [bootstrap.py](https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py) (using [these commands](https://github.com/JanitorTechnology/dockerfiles/blob/cdd566fee20a85cf7d2a94cfc162dfe74391cd72/firefox/firefox-git.dockerfile#L8-L9)), but if it installs a different Clang version, it doesn't show up in the logs.

Also, the logs seem to indicate that `clang-5.0`, `clang++-5.0` and `lld` are all correctly detected:

```
 0:05.26 checking for the target C compiler... /usr/bin/clang-5.0
 [...]
 0:05.86 checking for the target C++ compiler... /usr/bin/clang++-5.0
 [...]
 0:06.05 checking for the host C compiler... /usr/bin/clang-5.0
 [...]
 0:06.17 checking for the host C++ compiler... /usr/bin/clang++-5.0
 [...]
 0:06.45 checking for linker... lld
 [...]
 0:12.33 checking for llvm-config... not found
 0:12.34 ERROR: Could not find LLVM/Clang installation for compiling stylo build-time
 0:12.34 bindgen.  Please specify the 'LLVM_CONFIG' environment variable
 0:12.34 (recommended), pass the '--with-libclang-path' and '--with-clang-path'
 0:12.34 options to configure, or put 'llvm-config' in your PATH.  Altering your
 0:12.34 PATH may expose 'clang' as well, potentially altering your compiler,
 0:12.34 which may not be what you intended.
 0:12.38 *** Fix above errors and then restart with\
 0:12.38                "/usr/bin/make -f client.mk build"
 0:12.38 client.mk:360: recipe for target 'configure' failed
 0:12.38 make: *** [configure] Error 1
The command '/bin/sh -c ./mozilla/mach build' returned a non-zero code: 2
Exited with code 2
```

I suspect that the `configure` step was able to detect `llvm-config-4.0` in the `PATH` as a valid `llvm-config` candidate, but that it doesn't detect `llvm-config-5.0`. Maybe we should add 5.0 options in [/toolkit/moz.configure](https://dxr.mozilla.org/mozilla-central/source/toolkit/moz.configure#622)?

**Comment by jankeromnes** [comment]
Filed Firefox build config bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1398082

**Comment by jankeromnes** [comment]
Successfully fixed in https://github.com/mozilla/gecko-dev/commit/01d2ba9d5ff42ad16b82d711e36e35f22f9f7de6! 🎆

**Comment by sajattack** [comment]
I'm still getting this error after that commit.

**Comment by jankeromnes** [comment]
@sajattack that's unfortunate, thanks for reporting you still see this issue! Could you please describe exactly where you see it? E.g.

- If you are you using Janitor, which project image are you using (Firefox-hg, Firefox-git, Servo, Thunderbird?) and when was it built (in https://janitor.technology/containers/ you'll see "Built X time ago")?
- If you are using our Dockerfiles directly, when was yours image created? Is your tree up to date?

I'm happy to help troubleshooting this issue, but I'll need more information please. Thanks!

**Comment by jaj232** [comment]
@jankeromnes  I am also getting the same "Could not find LLVM/Clang installation.." error when trying to build Firefox.  I am using Ubuntu and following these instructions
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation

This worked before(as of a few months ago), but it is not working now(as of 10-2-2017), not sure why its throwing this error.  

clang -v     3.8.0-2ubuntu4  
llvm -v  (not showing anything, not sure if this is package name??)

Any help would be appreciated.  Thanks.

**Comment by sajattack** [comment]
Nevermind I was just missing clang/llvm

**Comment by jankeromnes** [comment]
> @jankeromnes I am also getting the same "Could not find LLVM/Clang installation.." error when trying to build Firefox.
> clang -v 3.8.0-2ubuntu4

It looks like your Clang version is `3.8`, whereas Firefox explicitly supports `3.9`, `4.0`, `5.0` and `6.0`: https://github.com/mozilla/gecko-dev/commit/01d2ba9d5ff42ad16b82d711e36e35f22f9f7de6

`3.8` is quite old, so I'd suggest upgrading to a more recent Clang if you can, e.g. `5.0` which was recently released. This should fix your issue.

Otherwise, you could also search for your particular `llvm-config` package name (maybe `llvm-config-mp-3.8` or `llvm-config-3.8`) and add the line `export LLVM_CONFIG=<your llvm-config here>` to your repository's `./mozconfig` (or `./.mozconfig`) file. That should work around the build issue.

> Nevermind I was just missing clang/llvm

Glad you sorted it out! Thanks for reporting back here, I'll close this issue again.
