### ISSUE TITLE
[chromium] git repo in new containers is in "detached HEAD" by default

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/dockerfiles#90]
In a brand new container:

```
user@065ba82c187c:~/chromium/src ((03ef2fd...)) $ git branch
* (HEAD detached at origin/master)
  master
```

**Comment by jankeromnes** [comment]
The current commands used to check out Chromium are [here](https://github.com/JanitorTechnology/dockerfiles/blob/540ba8d16d82beb71def934b866004eab2f380f2/chromium/chromium.dockerfile), but basically:

- [export CHROME_DEVEL_SANDBOX=""](https://github.com/JanitorTechnology/dockerfiles/blob/540ba8d16d82beb71def934b866004eab2f380f2/chromium/chromium.dockerfile#L17-L19)
- [fetch --nohooks chromium](https://github.com/JanitorTechnology/dockerfiles/blob/540ba8d16d82beb71def934b866004eab2f380f2/chromium/chromium.dockerfile#L26)
- [cd src && gclient runhooks --jobs=18](https://github.com/JanitorTechnology/dockerfiles/blob/540ba8d16d82beb71def934b866004eab2f380f2/chromium/chromium.dockerfile#L40-L41)
- [gn gen out/Default --args="enable_nacl=false is_component_build=true"](https://github.com/JanitorTechnology/dockerfiles/blob/540ba8d16d82beb71def934b866004eab2f380f2/chromium/chromium.dockerfile#L44)

@beaufortfrancois do you have any idea why the resulting repository is "HEAD detached at origin/master" instead of "HEAD == master == origin/master"?

**Comment by beaufortfrancois** [comment]
It is because the workflow now is to use `git new-branch foo` IIRC.

For info, linux setup instructions are available at https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md

**Comment by jankeromnes** [comment]
Ah, so a detached HEAD at `origin/master` is expected behavior. Thanks!

I'll close this issue then.
